---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule==2.22 ansible==2.9.4
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
  - pip install docker
  - pip install xmltodict
  - pip install jmespath
  - pip install lxml
script:
  - molecule lint
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
