---
- name: Persist sriov_numvfs with udev rule
  blockinfile:
    path: "{{ sriov_udev_rule_path }}"
    block: |
      {% for device in sriov_devices %}
      SUBSYSTEM=="net", ACTION=="add", KERNEL=="{{ device }}", RUN+="/usr/bin/sh -c 'echo {{ sriov_numvfs }} > /sys/class/net/{{ device }}/device/sriov_numvfs'"
      {% endfor %}
    marker_begin: BEGIN SRIOV
    mode: 0644
    owner: root
    group: root
    create: true
  become: true
  notify: "{{ sriov_restart_handler }}"

- name: Add iommu to kernel command line
  include_role:
    name: stackhpc.grubcmdline
  tags: skip_when_testing
  vars:
    kernel_cmdline:
      - intel_iommu=on
    kernel_cmdline_remove:
      - ^intel_iommu=
    kernel_restart_handler: "{{ sriov_restart_handler }}"
