---
- name: Make working directory
  file:
    state: directory
    path: "{{ sriov_workdir }}"

- name: Download MFT
  unarchive:
    src: "{{ sriov_mft_url }}"
    dest: "{{ sriov_workdir }}"
    remote_src: true

- name: Determine if we can run mst_status
  command: mst status
  become: true
  failed_when: false
  changed_when: false
  register: mst_status_result

- name: Install MFT
  command: "{{ sriov_workdir }}/{{ no_ext }}/install.sh"
  vars:
    # Strip the file extension
    no_ext: "{{ (sriov_mft_tarball | splitext)[0] }}"
  become: true
  register: mft_install_result
  when: mst_status_result.rc != 0

- name: "Run: mst start"
  command: mst start
  become: true
  tags:
    - skip_ansible_lint
    - skip_when_testing
  when: mft_install_result.changed

- name: Determine list of pci addresses
  # json output is broken
  # parse error: Expected value before ',' at line 88, column 4
  # https://bugs.launchpad.net/ubuntu/+source/lshw/+bug/1405873
  command: lshw -xml -class network
  become: true
  register: network_devices
  changed_when: false

- name: Set default value for sriov_pci_addrs
  set_fact:
    sriov_pci_addrs: []

- name: set_fact containing list of pci_address
  set_fact:
    sriov_pci_addrs: "{{ sriov_pci_addrs + [pci_addr] }}"
  vars:
    pci_addr: "{{ item.businfo | regex_replace('^pci@', '') }}"
  when:
    - item.logicalname in sriov_devices
  # to_json | from_json gets rid of ordered dicts
  with_items: "{{ network_devices.stdout | xml2dict | json_query('list.node') | to_json | from_json }}"

- name: "Display sriov_pci_addrs value"
  debug:
    var: sriov_pci_addrs

- include_tasks: mlxconfig.yml
  loop: "{{ sriov_pci_addrs }}"
  loop_control:
    loop_var: device
